### ISSUE TITLE
Does not recognize imported

### ISSUE THREAD

**Issue by guoquan** [krassowski/jupyterlab-go-to-definition#15] opened 2019-10-10 18:11 UTC
It would be good if it will point to the `import` statement when I `alt+click` on an imported class or object. For example,
```
from collections import OrderedDict
od = OrderedDict()
```
when I `alt+click` on  `OrderedDict()`, it would be good to lead me to `import OrderedDict`. Then I can use "jumping to file" to figure out further. Jumping the exactly where it is in another file would be even better, though maybe really complicated.

**Comment by krassowski** [comment] 2019-10-11 22:05
Thank you for your feedback @guoquan.

This feature was already implemented since 0.5.1, however it requires the user to configure the symlinks to workaround JupyterLab not allowing to open files from outside of the project root directory.

This was not well documented before - I have just improved the documentation so that this is more easily discoverable - please see [this new section in our README.md](https://github.com/krassowski/jupyterlab-go-to-definition#symlink-workaround-jump-to-any-file-outside-of-the-project-root).

For the binder example (with the current setup - this is not guaraneteed to work in the future) following commands are sufficient:

```bash
mkdir .jupyter_symlinks
cd .jupyter_symlinks
mkdir -p srv/conda/envs/notebook/lib
ln -s /srv/conda/envs/notebook/lib/python3.7 srv/conda/envs/notebook/lib/python3.7
```

where the path was determined with the help of the `python3 -v` command as [described in readme](https://github.com/krassowski/jupyterlab-go-to-definition#which-directories-to-symlink).

Please see this gif as an illustration:

![Jump to OrderedDict - binder example](https://user-images.githubusercontent.com/5832902/66687477-a29eeb80-ec7a-11e9-9ee2-c58f31a0b088.gif)

and note that I needed to execute the command before <kbd>alt</kbd>-clicking on the `OrderedDict`.

You may be also interested in checking out a newer [jupyterlab-lsp](https://github.com/krassowski/jupyterlab-lsp) project which also offers jumping to definition feature (and in principle can support the cross-file jumps without prior command execution in the kernel). 

I will be closing this issue as I manually confirmed that the requested feature works as expected - please feel free to reopen or comment if you think that something should be improved or that parts of the documentation are not clear.

**Closed by krassowski** 2019-10-11 22:05 UTC
